version: '3'

################################################################################################
#
# ref:
#   - https://taskfile.dev/#/usage
#
################################################################################################


#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
includes:
  os:
    taskfile: ./taskfile/Taskfile_{{OS}}.yml
    dir: ./taskfile/

  base:
    taskfile: ./taskfile/Taskfile_base.yml
    dir: ./taskfile/

  go:
    taskfile: ./taskfile/Taskfile_base_go.yml
    dir: ./taskfile/

  flutter:
    taskfile: ./taskfile/Taskfile_base_flutter.yml
    dir: ./taskfile/

  rust:
    taskfile: ./taskfile/Taskfile_base_rust.yml
    dir: ./taskfile/

  python:
    taskfile: ./taskfile/Taskfile_base_python.yml
    dir: ./taskfile/

  docker:
    taskfile: ./taskfile/Taskfile_infra_docker.yml
    dir: ./taskfile/

  git:
    taskfile: ./taskfile/Taskfile_infra_git.yml
    dir: ./taskfile/


################################################################################################

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

#
# global env: https://taskfile.dev/#/usage?id=environment-variables
#
env:
  ENV1: testing-env

# env file:
#dotenv:
#  - .env

################################################################################################

# task groups:
tasks:
  default:
    cmds:
      - task: echo

  init:
    cmds:
      - cp .env.local .env
      - task: flutter:init

  echo:
    cmds:
      - echo "hello world"

  use:
    cmds:
      - echo "setup user global taskfile root dir >> {{.TASK_ROOT_DIR}}"
      - mkdir -p {{.TASK_ROOT_DIR}}
      - echo "current dir >> $(pwd)"
      - ln -sf $(pwd)/ {{.TASK_ROOT_DIR}}   # link dir:
      - ls -al {{.TASK_ROOT_DIR}}
      - open {{.TASK_ROOT_DIR}}
    vars:
      TASK_ROOT_DIR: "~/.task/local/"
    ignore_error: true

  new:
    desc: "create flutter app"
    cmds:
      - task: flutter:new

  run:
    cmds:
      - task: flutter:run

  push:
    cmds:
      - task: base:push

  quick:
    cmds:
      - task: base:quick
