version: '3'


tasks:
  build:
    cmds:
      - task: init

  docker:build:
    cmds:
      - docker build

  py312:build:
    aliases: [ 'py312b', 'b312' ]
    cmds:
      - docker build -f ./Dockerfile.ubuntu -t py312:latest .
      - docker images | grep py
    dir: ./3.12/

  py312:test:
    aliases: [ 'py312t', 't312' ]
    cmds:
      - docker run --rm -it py312:latest bash
    ignore_error: true

  py312:build:test:
    aliases: [ 'py312bt', 'bt312' ]
    cmds:
      - task: py312:build
      - task: py312:test
    ignore_error: true

  py312:save:
    aliases: [ 'py312s','s312' ]
    cmds:
      - mkdir -p ./tmp
      - docker save py312:latest -o ./tmp/py312.tar
      - ls -al ./tmp
      - open ./tmp
    ignore_error: true

  py312:load:
    aliases: [ 'py312l', 'l312', 'py312:import' ]
    cmds:
      - docker load -i ./tmp/py312.tar
      - docker images | grep py
    ignore_error: true