version: '3'


tasks:
  build:
    cmds:
      - task: init

  docker:build:
    cmds:
      - docker build


  py312:test:
    aliases: [ 'py312t', 't312' ]
    cmds:
      - docker run --rm -it py312:latest bash

  py312:build:
    aliases: [ 'py312b', 'b312' ]
    cmds:
      - docker build -f ./Dockerfile.ubuntu -t py312:latest .
      - docker images | grep py
    dir: ./3.12/