version: "3"

##################################################################
#
# Staging 测试环境, k3s 集群搭建
#
##################################################################

includes:
  os:
    taskfile: ./Taskfile_{{OS}}.yml
    dir: .
    optional: true

tasks:
  init:
    cmds:
      - echo "hello world"
