version: "3"

includes:
  os:
    taskfile: ./Taskfile_{{OS}}.yml
    dir: .
    optional: true

tasks:
  default:
    cmds:
      - task: echo

  echo:
    cmd: echo "hello world"

  quick:
    cmds:
      - task: commit
      - task: pull
      - task: push

  commit:
    cmds:
      - git commit -m "update"

  push:
    cmds:
      - git push origin main --tags
      - repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git" '{print "https://github.com/"$1}'`; open $repo_url
      - echo "git push success"

  pull:
    cmds:
      - git config pull.rebase false
      - git pull

  stash:
    cmds:
      - git stash
