##########################################################################################
#                              redis service:
# ref:
#   - https://hub.docker.com/_/redis/
#   - https://hub.docker.com/r/bitnami/redis/
#   - https://yq.aliyun.com/articles/57953
#   - WEB UI:
#     - https://github.com/joeferner/redis-commander/blob/master/docker-compose.yml
#   - https://docs.docker.com/compose/reference/envvars/#compose_file#compose_project_name
#   - 本地浏览器访问:
#       - http://127.0.0.1:18081/
##########################################################################################

version: "3.3"

services:
  hello:
    image: hello-world:latest
    container_name: hello-world
