##########################################################################################
#                              jaeger: 分布式链路追踪
# ref:
#   - https://www.jaegertracing.io/docs/1.18/getting-started/
#     - 官方文档
#   - 本地浏览器访问:
#     - http://localhost:16686
#
##########################################################################################

version: '3'
services:
  jaeger:
    image: jaegertracing/all-in-one:1.18
    container_name: jaeger
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"







