##########################################################################################
#                              nats service:
# reference:
#   - https://github.com/hhstore/blog/issues/349
#   - https://docs.nats.io/running-a-nats-service/introduction/running#docker
#   - https://www.cnblogs.com/liang1101/p/6652830.html
#
# tags:
#   - https://hub.docker.com/_/nats/tags
#     - docker pull nats:alpine3.20
#
# usage:
#   - local web browser:
#     - http://localhost:8222/
#     - http://localhost:8222/varz
#     - http://localhost:8222/connz　
#     - http://localhost:8222/subscriptionsz
#     - http://localhost:8222/routez
#     - http://localhost:8222/routez?subs=1
#
##########################################################################################

version: '3.5'

services:
  nats-server:
    image: nats:alpine3.20
    container_name: nats
    restart: unless-stopped
    ports:
      - '4222:4222'
      - '6222:6222'
      - '8222:8222'
    networks:
      - nats_net


##########################################################################################
#                                 自定义依赖:
##########################################################################################

# 自定义网络:
networks:
  nats_net:


