##########################################################################################
#                              nats service:
# reference:
#   - https://github.com/hhstore/blog/issues/349
#   - https://docs.nats.io/running-a-nats-service/nats_docker#creating-a-nats-cluster-with-docker-compose
#   - https://docs.nats.io/running-a-nats-service/introduction/running#docker
#   - https://www.cnblogs.com/liang1101/p/6652830.html
#
# usage:
#   - local web browser:
#     - http://localhost:8222/
#     - http://localhost:8222/varz
#     - http://localhost:8222/connz　
#     - http://localhost:8222/subscriptionsz
#     - http://localhost:8222/routez
#     - http://localhost:8222/routez?subs=1
#
##########################################################################################

version: "3.5"

services:
  nats:
    image: nats
    container_name: nats
    ports:
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: [ "nats" ]

  nats-1:
    image: nats
    container_name: nats-1
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: [ "nats" ]
    depends_on: [ "nats" ]

  nats-2:
    image: nats
    container_name: nats-2
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: [ "nats" ]
    depends_on: [ "nats" ]

##########################################################################################
#                                 自定义依赖:
##########################################################################################

# 自定义网络:
networks:
  nats:
    name: nats




