##########################################################################################
#                              portainer service:
##########################################################################################

version: "3.4"

services:
  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    ports:
      - '${COMPOSE_IPAM_GATEWAY}:9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data


##########################################################################################
#                                 自定义依赖:
##########################################################################################

# 自定义数据卷:
volumes:
  portainer_data:
