#
# reference:
#   - https://lukasgeiter.github.io/mkdocs-awesome-nav/reference/
#

title: 中间件

preserve_directory_names: true

hide: true

flatten_single_child_sections: true

ignore: "*.hidden.md"

nav:
  - 概述: index.md

  - 服务发现: discovery
  - 配置中心: config
  - 负载均衡: loadbalancer
  - 链路追踪: tracing
  - 日志系统: logging
  - 监控系统: monitoring
  - 告警系统: alerting
  - 消息队列: queue
  - "*"
