version: '3'


tasks:
  build:
    cmds:
      - task: init

  docker:build:
    cmds:
      - docker build

  adb:build:
    aliases: [ 'android:build', 'ab' ]
    cmds:
      - docker build -f ./Dockerfile -t adb:latest .
      - docker images | grep adb
    dir: .

  # TODO X: fix for M1 Mac
  adb:build:amd64:
    aliases: [ 'android:build:amd64', 'abu' ]
    cmds:
      - docker build -f ./Dockerfile.amd64 -t adb:amd64 .
      - docker images | grep adb
    dir: .

  adb:test:
    aliases: [ 'android:build', 'at' ]
    cmds:
      - docker run --rm -it -p 5037:5037 adb:amd64 bash
    ignore_error: true

  # TODO X: fix for M1 Mac
  adb:test:amd64:
    aliases: [ 'android:build:amd64', 'atu' ]
    cmds:
      - docker run --rm -it -p 5037:5037 --platform linux/amd64 adb:amd64 bash
    ignore_error: true

  adb:build:test:
    aliases: [ 'android:build:test', 'abt' ]
    cmds:
      - task: adb:build
      - task: adb:test
    ignore_error: true

  adb:save:
    aliases: [ 'android:save','as' ]
    cmds:
      - mkdir -p ./tmp
      - docker save adb:latest -o ./tmp/adb.tar
      - ls -al ./tmp
      - open ./tmp
    ignore_error: true

  adb:load:
    aliases: [ 'android:load', 'al', 'adb:import' ]
    cmds:
      - docker load -i ./tmp/adb.tar
      - docker images | grep adb
    ignore_error: true