##########################################################################################
#                          prometheus + grafana
#
# ref:
#   - https://github.com/docker/awesome-compose/blob/master/prometheus-grafana/compose.yaml
#
# admin ui:
#   - https://localhost:3000
#      - admin/admin
#
##########################################################################################

version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - 9090:9090
    # restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 13000:3000
    # restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin # user admin:
      - GF_SECURITY_ADMIN_PASSWORD=admin # user password
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

volumes:
  prom_data:
