
user www-data; # user nginx; # 修改用户
worker_processes 4; # 工作进程数

error_log /var/log/nginx/error.log warn;
pid /var/run/nginx.pid;

daemon off; # 必须添加,docker中,需要阻止后台运行


events {
    worker_connections 1024;
}


http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
    '$status $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on; # 添加
    tcp_nodelay on; # 添加
    types_hash_max_size 2048; # 添加
    gzip on; # 添加
    gzip_disable "msie6"; # 添加

    keepalive_timeout 65;


    include /etc/nginx/conf.d/*.conf;
}