version: "3"



#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################

tasks:
  pdm:
    aliases: [ "pm" ]
    cmds:
      - pdm {{.CLI_ARGS}}

  kv:
    cmds:
      - python run_kv.py
    dir: ./src/try_nats

  pub:
    cmds:
      - python run_pub.py
    dir: ./src/try_nats

  sub:
    cmds:
      - python run_sub.py
    dir: ./src/try_nats

  sub:m:
    aliases: [ "multi:sub", "m:sub" ]
    cmds:
      - python run_multi_sub.py
    dir: ./src/try_nats