version: "3"



#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################

tasks:
  pdm:
    aliases: [ "pm" ]
    cmds:
      - pdm {{.CLI_ARGS}}

  kv:
    cmds:
      - python run_kv.py
    dir: ./src/try_nats

  pub:
    cmds:
      - python run_pub.py
    dir: ./src/try_nats

  sub:
    cmds:
      - python run_sub.py
    dir: ./src/try_nats

  sub:m:
    aliases: [ "multi:sub", "m:sub" ]
    cmds:
      - python run_multi_sub.py
    dir: ./src/try_nats

  ops:base:
    aliases: [ "compose:base" ]
    cmds:
      - docker-compose -f compose-base.yml {{.CLI_ARGS}}

  ops:sub:
    aliases: [ "compose:sub" ]
    cmds:
      - docker network create py_nats_net
      - docker network ls
      - docker-compose -f compose-sub.yml {{.CLI_ARGS}}
    ignore_error: true

  ops:pub:
    aliases: [ "compose:pub" ]
    cmds:
      - docker-compose -f compose-pub.yml {{.CLI_ARGS}}

  sub:up:
    cmds:
      - docker-compose -f compose-sub.yml up -d
      - docker-compose -f compose-sub.yml ps
      - docker-compose -f compose-sub.yml logs -f
    ignore_error: true
