version: '3'

includes:
  python:
    aliases: [ 'py' ]
    taskfile: ./python/
    dir: ./python/
    optional: true

  android:
    aliases: [ 'adb' ]
    taskfile: ./android/
    dir: ./android/
    optional: true

  ubuntu:
    aliases: [ 'ub' ]
    taskfile: ./ubuntu/
    dir: ./ubuntu/
    optional: true


tasks:
  build:
    cmds:
      - task: init

  docker:build:
    cmds:
      - docker build

  clean:
    aliases: [ 'c', 'rm' ]
    cmds:
      - docker image prune -f
      - docker images
      - docker container prune -f
      - docker ps -a