version: '3'

includes:
  python:
    aliases: [ 'py' ]
    taskfile: ./python/
    dir: ./python/
    optional: true

  ubuntu:
    aliases: [ 'ub' ]
    taskfile: ./ubuntu/
    dir: ./ubuntu/
    optional: true


tasks:
  build:
    cmds:
      - task: init

  docker:build:
    cmds:
      - docker build
