version: "3"

tasks:
  docker:
    aliases: ["d"]
    cmds:
      - docker {{.CLI_ARGS}}

  docker:build:
    cmds:
      - docker build {{.CLI_ARGS}}

  # for python3.12 + uv + cn mirror
  build:ubuntu22:py312:
    aliases: ["b22py"]
    cmds:
      - |
        docker build -f python.cn.Dockerfile \
          -t {{.IMAGE}}:{{.TAG}} \
          -t {{.IMAGE}}:{{.TAG}}-py312 \
          -t {{.IMAGE}}:{{.TAG}}-py312-{{.DATE}} \
          -t {{.IMAGE}}:{{.TAG}}-py312-latest \
          .
    dir: "22.04"
    vars:
      IMAGE: "ubuntu"
      TAG: "22-uv"
      DATE: "20260916" # todo x: 及时更新参数， 20260916 是 2026年9月16日的镜像构建时间

  run:ubuntu22:py312:
    aliases: ["r22py"]
    cmds:
      - docker run -it --rm {{.IMAGE}}:{{.TAG}} bash
    dir: "22.04"
    vars:
      IMAGE: "ubuntu"
      TAG: "22-uv"

  login:
    cmds:
      - echo $GITHUB_PUSH_TOKEN
      - echo $GITHUB_PUSH_TOKEN | docker login ghcr.io -u hhstore --password-stdin
    dotenv:
      - .env
      - ../../.env
      - ../../../.env

  tag:
    cmds:
      - docker tag {{.IMAGE}}:{{.TAG}} ghcr.io/{{.ORG}}/{{.IMAGE}}:{{.TAG}}
    vars:
      IMAGE: "ubuntu"
      TAG: "22-uv"
      ORG: "better-sre" # "hhstore"

  rel:
    aliases: ["push"]
    cmds:
      - docker tag {{.IMAGE}}:{{.TAG}} ghcr.io/{{.ORG}}/{{.IMAGE}}:{{.TAG}}
      - docker push ghcr.io/{{.ORG}}/{{.IMAGE}}:{{.TAG}}
    vars:
      IMAGE: "ubuntu"
      TAG: "22-uv"
      ORG: "better-sre" # "hhstore"

  clean:
    aliases: ["c", "rm"]
    cmds:
      - docker image prune -f
      - docker images
      - docker container prune -f
      - docker ps -a
