##########################################################################################
#                              consul service:
#
# Web UI:
#   - http://localhost:8500/ui
#
# lib & sdk:
#   - https://www.consul.io/api/libraries-and-sdks.html
#   - python: https://github.com/cablehead/python-consul
#
# ref:
#   - https://github.com/hashicorp/consul
#   - https://github.com/hashicorp/consul/blob/master/demo/docker-compose-cluster/docker-compose.yml
#
##########################################################################################


version: '3'

services:
  #################### agent  ##############################
  consul-agent-1: &consul-agent
    image: consul:latest
    networks:
      - consul-base
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  #################### server  ##############################
  consul-server-1: &consul-server
    <<: *consul-agent
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server

  #################### web ui  ##############################
  consul-server-bootstrap:
    <<: *consul-agent
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    environment:
      # new web ui:
      #   - v1.1.0
      #   - https://www.consul.io/intro/getting-started/ui.html#how-to-use-the-new-ui
      CONSUL_UI_BETA: 1  # 0

    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"


##########################################################################################
#         resource
##########################################################################################

networks:
  consul-base:
