version: "3"

#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
includes:
  # support cross-platform tasks
  os:
    taskfile: ./Taskfile_{{OS}}.yml
    dir: .
    optional: true

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

################################################################################################

# task groups:
tasks:
  default:
    cmds:
      - task: init

  init:
    cmds:
      - echo init

  install:
    cmds:
      - os:install:rust # auto-detect OS, cross-platform install
      - task: install:fleet

  install:fleet:
    cmds:
      - curl -L get.fleet.rs | sh
      - fleet -v

  install:volo:
    aliases: ["i:volo"]
    cmds:
      - cargo install volo-cli
      - volo help

  check:
    cmds:
      - task: sys:check
      - rustup --version
      - cargo --version
      - rustup toolchain list
      - rustup check

  sys:check:
    cmds:
      - task: os:check:sys:version
