nav:
  - "首页":
      index.md
      # - 首页: index.md
      # - 中间件: infra/index.md
      # - Docker: docker/index.md
      # - K3S: k3s/index.md
      # - Kubernetes: k8s/index.md
      # - 参考: reference/index.md
  - "👷🏻 Taskfile": taskfile # emoji: box 🥏 🖥️ 👷🏻
  - "🐍 Python": python # 🐍
  - "📦️ 中间件": infra
  - "☁️ Cloud": cloud
  - "🐋 Docker": docker
  - "🚀 K3S": k3s
  - "🛰️ K8S": k8s
  - "📚 参考": reference
  - "📝 其他": related.md
  - "*"
