version: "3"

tasks:
  install:
    cmds:
      - go install go-micro.dev/v4/cmd/micro@v4.6.0 # for go-micro v4 cli
      - micro -v
      - go install github.com/cosmtrek/air@latest
      - go install github.com/BurntSushi/toml/cmd/tomlv@master # https://pre-commit.com/hooks.html
      - air -v

  install:pkg:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - go get -u -v github.com/gogo/protobuf/proto
      - go install github.com/golang/protobuf/protoc-gen-go@latest
      - go install go-micro.dev/v4/cmd/protoc-gen-micro@v4
    ignore_error: true

  install:proto:
    cmds:
      - go get -u -v github.com/gogo/protobuf/protoc-gen-gofast
      - go get -u -v github.com/gogo/protobuf/proto
      - go get -u -v github.com/gogo/protobuf/jsonpb
      - go get -u -v github.com/gogo/protobuf/protoc-gen-gogo
      - go get -u -v github.com/gogo/protobuf/gogoproto

  kratos:install:
    cmds:
      - go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
      - ehco "now install go kratos tools"
      - go install github.com/go-kratos/kratos/cmd/kratos/v2@latest
      - go install github.com/go-kratos/kratos/cmd/protoc-gen-go-http/v2@latest
      - go install github.com/go-kratos/kratos/cmd/protoc-gen-go-errors/v2@latest
      - go install github.com/google/gnostic/cmd/protoc-gen-openapi@latest

  zero:install:
    cmds:
      - go get -u github.com/tal-tech/go-zero
      - GO111MODULE=on go get -u github.com/tal-tech/go-zero/tools/goctl

  install-proto:
    cmds:
      - go get -u -v github.com/gogo/protobuf/protoc-gen-gofast
      - go get -u -v github.com/gogo/protobuf/proto
      - go get -u -v github.com/gogo/protobuf/jsonpb
      - go get -u -v github.com/gogo/protobuf/protoc-gen-gogo
      - go get -u -v github.com/gogo/protobuf/gogoproto

  ################################################################################################

  version:
    cmds:
      - go version

  init:
    cmds:
      - task: tidy

  tidy:
    cmds:
      - go mod tidy -v

  get:
    cmds:
      - go get -u -v github.com/tal-tech/go-zero

  ################################################################################################

  proto-gen-all:
    cmds:
      - cd ..
      - |
        find ./app -iname "*.proto" -exec \
        protoc -I=. \
        -I=${GOPATH}/src \
        -I=${GOPATH}/src/github.com/gogo/protobuf/protobuf \
        --proto_path=. \
        --gofast_out=plugins=grpc:. \
        {} \;

  proto-gen-micro:
    cmds:
      - cd ..
      - |
        find ./creator-mate/app -iname "*.proto" -exec \
        protoc --proto_path=. \
        --micro_out=${MODIFY}:. \
        --go_out=paths=source_relative:. \
        {} \;

  proto-gen-data:
    cmds:
      - cd ..
      - |
        find ./creator-mate/app -iname "*.proto" -exec \
        protoc --proto_path=. \
        --micro_out=${MODIFY}:. \
        --go_out=paths=source_relative:. \
        {} \;

  ################################################################################################

  app-gen-basic:
    cmds:
      - cd ..
      - cd app/basic
      - cookiecutter https://github.com/better-go/cookiecutter-go.git --directory="single-app/go-zero"

  app-gen-biz:
    cmds:
      - cd ..
      - cd app/biz
      - cookiecutter https://github.com/better-go/cookiecutter-go.git --directory="single-app/go-zero"
